name: itemID_Toggle
main: spokkernetwork\ItemID\ItemID
author: SpokkerNetwork
version: 1.0.0
api: 
- 1.0.0
- 1.1.0
- 2.0.0

commands:
  itemid:    
    description: Ativar popup de ItemID
    permission: itemid.command
    aliases:
    - id
    - itemid

permissions:
  emotes.command:
    default: op